### ISSUE TITLE
Doesn't work with last build

### ISSUE THREAD

**Issue by vojtasvoboda** [rainlab/sitemap-plugin#21]
It seems that Save on Sitemap doesn't work with last build 293. I tried to uninstall & install fresh and also tried Force Update. Error:

![snimek obrazovky 2015-09-08 v 11 11 56](https://cloud.githubusercontent.com/assets/374917/9731026/ca8e02d4-561a-11e5-95c4-20dd34c86396.png)

Call stack:

```
exception 'Exception' with message 'Unexpected type of array, should attribute "items" be jsonable?' in /www/vendor/october/rain/src/Database/Model.php:1110
Stack trace:
#0 /www/vendor/october/rain/src/Database/Model.php(1151): October\Rain\Database\Model->saveInternal(Array)
#1 /www/modules/backend/behaviors/FormController.php(261): October\Rain\Database\Model->save(NULL, 'YXAiDGNoZtoeLOu...')
#2 [internal function]: Backend\Behaviors\FormController->update_onSave('1')
#3 /www/vendor/october/rain/src/Extension/ExtendableTrait.php(311): call_user_func_array(Array, Array)
#4 /www/vendor/october/rain/src/Extension/Extendable.php(44): October\Rain\Extension\Extendable->extendableCall('update_onSave', Array)
#5 [internal function]: October\Rain\Extension\Extendable->__call('update_onSave', Array)
#6 [internal function]: RainLab\Sitemap\Controllers\Definitions->update_onSave('1')
#7 /www/modules/backend/classes/Controller.php(527): call_user_func_array(Array, Array)
#8 /www/modules/backend/classes/Controller.php(423): Backend\Classes\Controller->runAjaxHandler('onSave')
#9 /www/modules/backend/classes/Controller.php(233): Backend\Classes\Controller->execAjaxHandlers()
#10 /www/modules/backend/classes/BackendController.php(95): Backend\Classes\Controller->run('update', Array)
#11 [internal function]: Backend\Classes\BackendController->run('rainlab/sitemap...')
```

**Comment by vojtasvoboda** [comment]
Tested and works :+1:
